# Generated by Django 4.1.7 on 2023-03-30 10:16

from django.db import migrations, models
import django_quill.fields
import events_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=events_app.models.Events.user_directory_path)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('date_open', models.DateField()),
                ('date_closes', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('COMINGSOON', 'Cooming Soon')], default='OPEN', max_length=10)),
                ('description', django_quill.fields.QuillField()),
                ('registration_link', models.URLField()),
                ('price', models.IntegerField()),
                ('highlight', models.TextField(choices=[('TRUE', 'Iya'), ('FALSE', 'Tidak')], default='FALSE', max_length=6)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
