# Generated by Django 4.1.7 on 2023-04-04 20:09

from django.db import migrations, models
import events_app.models
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=events_app.models.Events.user_directory_path)),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('COMINGSOON', 'Cooming Soon')], default='OPEN', max_length=10)),
                ('description', wagtail.fields.RichTextField()),
                ('registration_link', models.URLField()),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Acara',
                'verbose_name_plural': 'Event Halo Beasiswa',
            },
        ),
    ]
