# Generated by Django 4.1.7 on 2023-04-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='instagram_feed_link',
            field=models.URLField(default=''),
        ),
    ]
