# Generated by Django 4.1.7 on 2023-03-28 11:03

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_events_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
