# Generated by Django 4.1.5 on 2023-02-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
