# Generated by Django 4.1.7 on 2023-04-04 20:09

import countries_app.models
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountriesToStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=countries_app.models.CountriesToStudy.user_directory_path)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('COMINGSOON', 'Cooming Soon')], default='OPEN', max_length=10)),
                ('description', wagtail.fields.RichTextField()),
                ('registration_link', models.URLField()),
                ('booklet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'verbose_name': 'Negara Tujuan',
                'verbose_name_plural': 'Negara Tujuan Kuliah Halo Beasiswa',
            },
        ),
    ]
