# Generated by Django 4.1.7 on 2023-03-30 10:17

import countries_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('picture', models.ImageField(upload_to=countries_app.models.Countries.user_directory_path)),
                ('date_open', models.DateField()),
                ('date_closes', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('COMINGSOON', 'Cooming Soon')], default='OPEN', max_length=10)),
                ('description', models.TextField()),
                ('registration_link', models.URLField()),
                ('booklet_link', models.URLField()),
                ('highlight', models.TextField(choices=[('TRUE', 'Iya'), ('FALSE', 'Tidak')], default='FALSE', max_length=6)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
